### PR TITLE
fixing the library import issue by using  webpack (please don't merge this PR)

### PR DESCRIPTION
**Pull request by aldeez988**

### CODE REVIEW

**Comment by samatar26** [comment]
@aldeez988 

Awesome progress on making the importing work! :100: 

I've got a couple of points regarding this PR:

The main 2 things required to make this library work in other packages is:

1 - Using the `module` field in the package.json to let bundlers like webpack/create-react-app know where the entry point of your library is. And you've done that :100: 

2 - Transpiling the code to ES5/6 to make it work in the browser. The main reason for this is that `node_modules` aren't transpiled by default usually. `create-react-app` does, but only using `babel-preset-env` and not `babel-preset-react` which is why you get the error once it reaches the JSX syntax.

So there's no need to use a bundler like webpack and make all these changes. I'd personally open a new PR and just use babel.

**Comment by samatar26** [comment]
Steps required for new PR: 

- Install as a dev dependency `@babel/cli`, `@babel/core`, `@babel/preset-env`, `@babel/preset-react` 

- Add a build script to your package.json like so: 
`"build": babel src/components/index.js --out-dir dist`

Add a `.babelrc` to the root of the project containing your babel configuration (We want to transpile our react code, i.e. the JSX syntax, etc): 

```{
presets: ["@babel/preset-react", "@babel/preset-env"]
}```

(babel/preset-env allows babel to transpile your code down to the JavaScript version the browsers you target support.)

**Comment by samatar26** [comment]
@aldeez988  Can't you close this PR?

**Comment by aldeez988** [comment]
> @aldeez988 Can't you close this PR?

Closed now

**Pull request closed without merging**
